apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs
    tier: backend
    deployedBy: deploy-node-app
  name: nodejs
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: your-app-name
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: your-app-name
        tier: backend
        deployedBy: deploy-node-app
    spec:
      containers:
        - image: 'nileshparab/nodejs:dc09a22-1583921697'
          imagePullPolicy: Always
          name: nodejs
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 128Mi
            requests:
              cpu: 3m
              memory: 64Mi
          command:
            - node
            - index.js
          envFrom: []
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  imagePullSecrets:
    - name: nodejs-regcred

