apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nodejs
    tier: backend

